### ISSUE TITLE
virData示例 js报错

### ISSUE THREAD

**Issue by hrbzcj** [kirakiray/stanz#23]
[https://github.com/kirakiray/stanz/blob/master/doc/cn/method_about_data.md#virdata](https://github.com/kirakiray/stanz/blob/master/doc/cn/method_about_data.md#virdata)

**Comment by kirakiray** [comment]
非常感谢你的反馈，发现文档有遗漏；

stanz现在更新到6.0，virData api  已经更新，改为如下的使用方法

```javascript
let mapData = obj.virData({
    // 映射
    key: "tag",
    mapValue: {
        "p-ele": "pre-ele",
        "p-text": "pre-text",
        "p-pic": "pre-pic"
    }
});
```

原先 type被取消，直接改用mapValue属性
